config/routes.rb
Rails.application.routes.draw do
  resources :centros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/centro.rb
class Centro < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/centros_controller.rb
class CentrosController < ApplicationController
  before_action :set_centro, only: [:show, :edit, :update, :destroy]

  # GET /centros
  # GET /centros.json
  def index
    @centros = Centro.all
  end

  # GET /centros/1
  # GET /centros/1.json
  def show
  end

  # GET /centros/new
  def new
    @centro = Centro.new
  end

  # GET /centros/1/edit
  def edit
  end

  # POST /centros
  # POST /centros.json
  def create
    @centro = Centro.new(centro_params)

    respond_to do |format|
      if @centro.save
        format.html { redirect_to @centro, notice: 'Centro was successfully created.' }
        format.json { render :show, status: :created, location: @centro }
      else
        format.html { render :new }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /centros/1
  # PATCH/PUT /centros/1.json
  def update
    respond_to do |format|
      if @centro.update(centro_params)
        format.html { redirect_to @centro, notice: 'Centro was successfully updated.' }
        format.json { render :show, status: :ok, location: @centro }
      else
        format.html { render :edit }
        format.json { render json: @centro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /centros/1
  # DELETE /centros/1.json
  def destroy
    @centro.destroy
    respond_to do |format|
      format.html { redirect_to centros_url, notice: 'Centro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_centro
      @centro = Centro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def centro_params
      params.require(:centro).permit(:nombre, :descripcion, :url, :latitud, :longitud)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centros_helper.rb
module CentrosHelper
end

app/views/centros/_form.html.erb
<%= form_with(model: centro, local: true) do |form| %>
  <% if centro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(centro.errors.count, "error") %> prohibited this centro from being saved:</h2>

      <ul>
      <% centro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :latitud %>
    <%= form.text_field :latitud %>
  </div>

  <div class="field">
    <%= form.label :longitud %>
    <%= form.text_field :longitud %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/centros/edit.html.erb
<h1>Editing Centro</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Show', @centro %> |
<%= link_to 'Back', centros_path %>

app/views/centros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Centros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Url</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @centros.each do |centro| %>
      <tr>
        <td><%= centro.nombre %></td>
        <td><%= centro.descripcion %></td>
        <td><%= centro.url %></td>
        <td><%= centro.latitud %></td>
        <td><%= centro.longitud %></td>
        <td><%= link_to 'Show', centro %></td>
        <td><%= link_to 'Edit', edit_centro_path(centro) %></td>
        <td><%= link_to 'Destroy', centro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Centro', new_centro_path %>

app/views/centros/new.html.erb
<h1>New Centro</h1>

<%= render 'form', centro: @centro %>

<%= link_to 'Back', centros_path %>

app/views/centros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @centro.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @centro.descripcion %>
</p>

<p>
  <strong>Url:</strong>
  <%= @centro.url %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @centro.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @centro.longitud %>
</p>

<%= link_to 'Edit', edit_centro_path(@centro) %> |
<%= link_to 'Back', centros_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CentroAtencionMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>